name: build-and-test
on: [pull_request, push]
jobs:
  linux:
    name: Ubuntu, Go ${{matrix.go}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.12', '1.13', '1.14', '1.15', '1.16', '1.17', 'tip' ]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{matrix.go}}
        - run: apt-get install libusb-1.0-0-dev
        - run: go get golang.org/x/tools/cmd/cover
        - run: go get golang.org/x/lint/golint
        - run: go get github.com/mattn.goveralls
        - run: $HOME/gopath/bin/golint ./...
        - run: sh ./.github/test-coverage.sh
