name: build-and-test
on: [pull_request, push, workflow_dispatch]
jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: DIFF="$( find . -name '*.go' -print0 | xargs -0 gofmt -l )"; if [ -n "$DIFF" ]; then echo "Files not formatted, run gofmt:"; echo "$DIFF"; exit 1; fi
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: go install golang.org/x/tools/cmd/cover@latest
      - run: go install golang.org/x/lint/golint@latest
      - run: $HOME/go/bin/golint -set_exit_status ./...
      - run: sh ./.github/test-coverage.sh
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.merged
          ignore: libusb.go,error.go
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: msys2/setup-msys2@v2
        with:
          install: |-
            mingw64/mingw-w64-x86_64-libusb
            mingw64/mingw-w64-x86_64-pkg-config
      - run: echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: go test ./...
      - run: go run ./lsusb
