name: build-and-test
on: [pull_request, push]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get golang.org/x/lint/golint
      - run: $HOME/go/bin/golint ./...
      - run: sh ./.github/test-coverage.sh
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.merged
          ignore: libusb.go,error.go
  windows:
    runs-on: windows-2019
    env:
      PKG_CONFIG_PATH: c:\msys64\mingw64\lib\pkgconfig
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: |-
            base-devel
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-gcc
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test ./...
