name: build-and-test
on: [pull_request, push]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get golang.org/x/lint/golint
      - run: $HOME/go/bin/golint ./...
      - run: sh ./.github/test-coverage.sh
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.merged
          ignore: libusb.go,error.go
  windows:
    runs-on: windows-2019
    env:
      PKG_CONFIG_PATH: D:\a\_temp\msys64\mingw64\lib\pkgconfig
      CGO_CFLAGS: -ID:\a\_temp\msys64\mingw64\include\libusb-1.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: pacman --noconfirm -S mingw64/mingw-w64-x86_64-go mingw64/mingw-w64-x86_64-libusb
      - shell: msys {0}
        run: go test ./...
