name: build-and-test
on: [pull_request, push]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get golang.org/x/lint/golint
      - run: $HOME/go/bin/golint ./...
      - run: sh ./.github/test-coverage.sh
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.merged
          ignore: libusb.go,error.go
  windows:
    runs-on: windows-2022
    env:
      PKG_CONFIG_PATH: C:\msys64\mingw64\lib\pkgconfig
    defaults:
      run:
        shell: c:\msys64\usr\bin\bash.exe --noprofile --norc -eo pipefail {0}
    steps:
      - uses: actions/checkout@v2
      - run: /usr/bin/pacman --noconfirm -R mingw-w64-x86_64-pkgconf
      - run: /usr/bin/pacman --noconfirm -S mingw64/mingw-w64-x86_64-go mingw64/mingw-w64-x86_64-libusb mingw64/mingw-w64-x86_64-pkg-config
      - run: /usr/bin/pkg-config --cflags libusb-1.0
      # - run: go test ./...
